/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/kart.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["KART-OBJ_1"].geometry}
          material={materials.Telaio}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["KART-OBJ_2"].geometry}
          material={materials.Carena}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["KART-OBJ_3"].geometry}
          material={materials.Gomma}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["KART-OBJ_4"].geometry}
          material={materials.Sedile}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/kart.glb");
